/**
 * DSF-SE API
 * Sample version of DSF-SE API for communication with the professional UI
 *
 * OpenAPI spec version: 3
 * Contact: sisay.adugna.chala@fit.fraunhofer.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Photovoltaic { 
    id: string;
    /**
     * ID for the connected node
     */
    node: string;
    inverterEfficiency?: number;
    phases: number;
    power: number;
    powerunit?: string;
    powerfactor?: number;
    bus1: string;
    voltage: number;
    effcurve: string;
    ptcurve: string;
    daily: string;
    tdaily?: string;
    pf: number;
    voltageunit?: string;
}
