/**
 * DSF-SE API
 * Sample version of DSF-SE API for communication with the professional UI
 *
 * OpenAPI spec version: 3
 * Contact: sisay.adugna.chala@fit.fraunhofer.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Powerline { 
    id: string;
    /**
     * ID for the connected node
     */
    bus1?: string;
    phases?: number;
    /**
     * ID for the connected node
     */
    bus2?: string;
    length?: number;
    unitlength: string;
    linecode?: string;
    r1?: number;
    r0?: number;
    x1?: number;
    x0?: number;
    c1?: number;
    c0?: number;
    _switch?: boolean;
}
