/**
 * DSF-SE API
 * Sample version of DSF-SE API for communication with the professional UI
 *
 * OpenAPI spec version: 3
 * Contact: sisay.adugna.chala@fit.fraunhofer.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Capacitor } from './capacitor';
import { ChargingPoint } from './chargingPoint';
import { Linecode } from './linecode';
import { Load } from './load';
import { Loadshape } from './loadshape';
import { Photovoltaic } from './photovoltaic';
import { PowerProfile } from './powerProfile';
import { Powerline } from './powerline';
import { RegControl } from './regControl';
import { Storage } from './storage';
import { Transformer } from './transformer';
import { Tshape } from './tshape';
import { XYCurve } from './xYCurve';


export interface Radial { 
    radialId?: string;
    transformer?: Array<Transformer>;
    loads?: Array<Load>;
    powerProfiles?: Array<PowerProfile>;
    powerLines?: Array<Powerline>;
    photovoltaics?: Array<Photovoltaic>;
    storageUnits?: Array<Storage>;
    chargingPoints?: Array<ChargingPoint>;
    linecode?: Array<Linecode>;
    capacitor?: Array<Capacitor>;
    voltageRegulator?: Array<RegControl>;
    xycurves?: Array<XYCurve>;
    loadshapes?: Array<Loadshape>;
    tshapes?: Array<Tshape>;
}
