/**
 * DSF-SE API
 * Sample version of DSF-SE API for communication with the professional UI
 *
 * OpenAPI spec version: 3
 * Contact: sisay.adugna.chala@fit.fraunhofer.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Duration } from './duration';


export interface Simulation { 
    gridId?: string;
    duration?: Duration;
    /**
     * Lower threshold in % for voltage error
     */
    thresholdLow?: number;
    /**
     * Medium threshold in % for voltage error
     */
    thresholdMedium?: number;
    /**
     * Maximum threshold in % for voltage error
     */
    thresholdHigh?: number;
}
