/**
 * DSF-SE API
 * Sample version of DSF-SE API for communication with the professional UI
 *
 * OpenAPI spec version: 3
 * Contact: sisay.adugna.chala@fit.fraunhofer.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Storage { 
    id: string;
    /**
     * ID for the connected node
     */
    node: string;
    soC: number;
    doD: number;
    soH?: number;
    energy?: number;
    inverterEfficiency?: number;
    phases?: number;
    voltage?: number;
    voltageunit?: string;
    power?: number;
    powerunit?: string;
    powerfactor?: number;
}
