/**
 * DSF-SE API
 * Sample version of DSF-SE API for communication with the professional UI
 *
 * OpenAPI spec version: 3
 * Contact: sisay.adugna.chala@fit.fraunhofer.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Winding { 
    /**
     * Integer representing the winding witch will become the active winding for subsequent data
     */
    wdg?: number;
    /**
     * Definition for the connector of this winding (each winding is connected to one terminal of the transformator and, hence, to one bus
     */
    bus?: string;
    connectionType?: string;
    /**
     * Rated voltage of this winding, kV
     */
    kV?: number;
    /**
     * base kVA rating for windings
     */
    kVA?: number;
    percentResistance?: number;
    xlt?: number;
    xht?: number;
}
